import { defineConfig } from "oxfmt";
import ultracite from "ultracite/oxfmt";

export default defineConfig({
  ...ultracite,
  // The docs search index is generated by the icon build; skip formatting it
  // (the other generated icon dirs are already covered by .gitignore).
  ignorePatterns: [
    ...(ultracite.ignorePatterns ?? []),
    "apps/docs/src/icons-search-index.json",
  ],
});
