import "server-only";
import { readFile } from "node:fs/promises";
import path from "node:path";

import { getIconDoc } from "@/lib/icon-detail";

export interface IconConcept {
  concept: string;
  /** Optional prose from the data file. Absent for a bare `concept -> slug`. */
  note?: string;
  slug: string;
}

/**
 * `_concepts.json` is authored in the icon package and lands here through
 * `npm run copy-icons`, which `docs#build` already depends on. It is read at
 * build time rather than imported, because it may not exist: an import of a
 * missing JSON file fails the typecheck and the build, and this page is
 * supposed to ship an empty table instead.
 *
 * One literal path, not a search. A `..` traversal up to the package makes
 * Turbopack trace the whole monorepo into the server bundle (it warns at
 * ~11,000 files), which is a real bundling cost to save a `copy-icons` run
 * the build performs anyway.
 */
const CONCEPTS_PATH = path.join(
  process.cwd(),
  "src",
  "icons-data",
  "_concepts.json"
);

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

/** Pull `{ concept, slug, note }` out of one entry, whatever shape it takes. */
const readEntry = (concept: string, value: unknown): IconConcept | null => {
  if (typeof value === "string") {
    return { concept, slug: value };
  }
  if (isRecord(value)) {
    const slug = value.icon ?? value.slug;
    if (typeof slug === "string") {
      return {
        concept,
        note: typeof value.note === "string" ? value.note : undefined,
        slug,
      };
    }
  }
  return null;
};

/**
 * Accepts the `{ "concepts": { ... } }` wrapper the file actually uses, a bare
 * `{ concept: slug }` map, and a list of records. The wrapper also carries a
 * `description` key, so reading the top level as the table directly would
 * produce a bogus entry; and the file is generated by the icon package rather
 * than written here, so a reshape upstream should degrade to fewer rows rather
 * than a broken route.
 */
const normalizeConcepts = (parsed: unknown): IconConcept[] => {
  const source =
    isRecord(parsed) && "concepts" in parsed ? parsed.concepts : parsed;

  if (Array.isArray(source)) {
    return source.flatMap((item) => {
      if (!isRecord(item)) {
        return [];
      }
      const concept = item.concept ?? item.name;
      if (typeof concept !== "string") {
        return [];
      }
      const entry = readEntry(concept, item);
      return entry ? [entry] : [];
    });
  }

  if (isRecord(source)) {
    return Object.entries(source).flatMap(([concept, value]) => {
      const entry = readEntry(concept, value);
      return entry ? [entry] : [];
    });
  }

  return [];
};

export interface ConceptsTable {
  /** Entries whose target slug does not resolve to a real icon. */
  unresolved: string[];
  concepts: IconConcept[];
  /** False when `_concepts.json` is not in the tree yet. */
  present: boolean;
}

const readConceptsFile = async (): Promise<string | null> => {
  try {
    return await readFile(CONCEPTS_PATH, "utf-8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return null;
    }
    throw error;
  }
};

export const getConceptsTable = async (): Promise<ConceptsTable> => {
  "use cache";

  const raw = await readConceptsFile();
  if (raw === null) {
    return { concepts: [], present: false, unresolved: [] };
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    // The file is regenerated by `copy-icons`; catching a half-written read
    // keeps a build from failing on someone else's in-flight edit.
    return { concepts: [], present: false, unresolved: [] };
  }

  const entries = normalizeConcepts(parsed).toSorted((a, b) =>
    a.concept.localeCompare(b.concept)
  );

  const concepts: IconConcept[] = [];
  const unresolved: string[] = [];
  for (const entry of entries) {
    if (getIconDoc(entry.slug)) {
      concepts.push(entry);
    } else {
      unresolved.push(entry.concept);
    }
  }

  return { concepts, present: true, unresolved };
};
