// Auto-generated by scripts/generate-lucide-compat.js — do not edit manually.

import { createLucideIcon } from './create-lucide-icon'
export type { LucideProps, LucideIcon } from './lucide-types'

import _ChevronDown from './chevron-down'
export const ChevronDown = createLucideIcon('ChevronDown', _ChevronDown)
import _ChevronUp from './chevron-up'
export const ChevronUp = createLucideIcon('ChevronUp', _ChevronUp)
import _ChevronLeft from './chevron-left'
export const ChevronLeft = createLucideIcon('ChevronLeft', _ChevronLeft)
import _ChevronRight from './chevron-right'
export const ChevronRight = createLucideIcon('ChevronRight', _ChevronRight)
import _ChevronsUpDown from './chevron-grabber-vertical'
export const ChevronsUpDown = createLucideIcon('ChevronsUpDown', _ChevronsUpDown)
import _ArrowDown from './arrow-down'
export const ArrowDown = createLucideIcon('ArrowDown', _ArrowDown)
import _ArrowUp from './arrow-up'
export const ArrowUp = createLucideIcon('ArrowUp', _ArrowUp)
import _ArrowLeft from './arrow-left'
export const ArrowLeft = createLucideIcon('ArrowLeft', _ArrowLeft)
import _ArrowRight from './arrow-right'
export const ArrowRight = createLucideIcon('ArrowRight', _ArrowRight)
import _ArrowUpDown from './arrow-top-bottom'
export const ArrowUpDown = createLucideIcon('ArrowUpDown', _ArrowUpDown)
import _ArrowUpRight from './arrow-up-right'
export const ArrowUpRight = createLucideIcon('ArrowUpRight', _ArrowUpRight)
import _ArrowDownLeft from './arrow-down-left'
export const ArrowDownLeft = createLucideIcon('ArrowDownLeft', _ArrowDownLeft)
import _ArrowDownRight from './arrow-down-right'
export const ArrowDownRight = createLucideIcon('ArrowDownRight', _ArrowDownRight)
import _ArrowUpLeft from './arrow-up-left'
export const ArrowUpLeft = createLucideIcon('ArrowUpLeft', _ArrowUpLeft)
import _ArrowDownFromLine from './arrow-from-line-down'
export const ArrowDownFromLine = createLucideIcon('ArrowDownFromLine', _ArrowDownFromLine)
import _ArrowUpFromLine from './arrow-from-line-up'
export const ArrowUpFromLine = createLucideIcon('ArrowUpFromLine', _ArrowUpFromLine)
import _CornerDownLeft from './arrow-corner-down-left'
export const CornerDownLeft = createLucideIcon('CornerDownLeft', _CornerDownLeft)
import _Check from './check'
export const Check = createLucideIcon('Check', _Check)
import _CheckCircle2 from './circle-check'
export const CheckCircle2 = createLucideIcon('CheckCircle2', _CheckCircle2)
import _CircleCheck from './circle-check'
export const CircleCheck = createLucideIcon('CircleCheck', _CircleCheck)
import _Circle from './circle-outline'
export const Circle = createLucideIcon('Circle', _Circle)
import _X from './cross-large'
export const X = createLucideIcon('X', _X)
import _AlertCircle from './circle-exclamation'
export const AlertCircle = createLucideIcon('AlertCircle', _AlertCircle)
import _CircleAlert from './circle-exclamation'
export const CircleAlert = createLucideIcon('CircleAlert', _CircleAlert)
import _AlertTriangle from './triangle-exclamation'
export const AlertTriangle = createLucideIcon('AlertTriangle', _AlertTriangle)
import _TriangleAlert from './triangle-exclamation'
export const TriangleAlert = createLucideIcon('TriangleAlert', _TriangleAlert)
import _Info from './info'
export const Info = createLucideIcon('Info', _Info)
import _CircleX from './circle-x'
export const CircleX = createLucideIcon('CircleX', _CircleX)
import _CircleHelp from './circle-questionmark'
export const CircleHelp = createLucideIcon('CircleHelp', _CircleHelp)
import _BadgeCheck from './verified-check'
export const BadgeCheck = createLucideIcon('BadgeCheck', _BadgeCheck)
import _ShieldAlert from './shield-break'
export const ShieldAlert = createLucideIcon('ShieldAlert', _ShieldAlert)
import _Plus from './plus-large'
export const Plus = createLucideIcon('Plus', _Plus)
import _Minus from './minus-large'
export const Minus = createLucideIcon('Minus', _Minus)
import _Search from './magnifying-glass'
export const Search = createLucideIcon('Search', _Search)
import _Filter from './filter-1'
export const Filter = createLucideIcon('Filter', _Filter)
import _Settings from './settings-gear-1'
export const Settings = createLucideIcon('Settings', _Settings)
import _Settings2 from './settings-slider-hor'
export const Settings2 = createLucideIcon('Settings2', _Settings2)
import _Pencil from './pencil'
export const Pencil = createLucideIcon('Pencil', _Pencil)
import _Trash from './trash-can-2'
export const Trash = createLucideIcon('Trash', _Trash)
import _Trash2 from './trash-can-2'
export const Trash2 = createLucideIcon('Trash2', _Trash2)
import _Ellipsis from './dot-grid-1x3-horizontal'
export const Ellipsis = createLucideIcon('Ellipsis', _Ellipsis)
import _EllipsisVertical from './dot-grid-1x3-vertical'
export const EllipsisVertical = createLucideIcon('EllipsisVertical', _EllipsisVertical)
import _MoreHorizontal from './dot-grid-1x3-horizontal'
export const MoreHorizontal = createLucideIcon('MoreHorizontal', _MoreHorizontal)
import _MoreVertical from './dot-grid-1x3-vertical'
export const MoreVertical = createLucideIcon('MoreVertical', _MoreVertical)
import _Copy from './copy-simple'
export const Copy = createLucideIcon('Copy', _Copy)
import _Clipboard from './clipboard'
export const Clipboard = createLucideIcon('Clipboard', _Clipboard)
import _ClipboardList from './square-checklist'
export const ClipboardList = createLucideIcon('ClipboardList', _ClipboardList)
import _GripVertical from './dot-grid-2x3-vertical'
export const GripVertical = createLucideIcon('GripVertical', _GripVertical)
import _PlusCircle from './circle-plus'
export const PlusCircle = createLucideIcon('PlusCircle', _PlusCircle)
import _ArchiveX from './archive'
export const ArchiveX = createLucideIcon('ArchiveX', _ArchiveX)
import _User from './person-simple'
export const User = createLucideIcon('User', _User)
import _User2 from './person-simple'
export const User2 = createLucideIcon('User2', _User2)
import _CircleUser from './circle-person'
export const CircleUser = createLucideIcon('CircleUser', _CircleUser)
import _Users from './people'
export const Users = createLucideIcon('Users', _Users)
import _UserPlus from './people-add'
export const UserPlus = createLucideIcon('UserPlus', _UserPlus)
import _Bell from './bell'
export const Bell = createLucideIcon('Bell', _Bell)
import _BellOff from './bell-off'
export const BellOff = createLucideIcon('BellOff', _BellOff)
import _BellRing from './bell-alarm'
export const BellRing = createLucideIcon('BellRing', _BellRing)
import _Mail from './email-2'
export const Mail = createLucideIcon('Mail', _Mail)
import _MailOpen from './email-3'
export const MailOpen = createLucideIcon('MailOpen', _MailOpen)
import _Send from './send'
export const Send = createLucideIcon('Send', _Send)
import _MessageSquare from './bubble-3'
export const MessageSquare = createLucideIcon('MessageSquare', _MessageSquare)
import _Inbox from './inbox-empty'
export const Inbox = createLucideIcon('Inbox', _Inbox)
import _Menu from './bars-three'
export const Menu = createLucideIcon('Menu', _Menu)
import _Home from './home'
export const Home = createLucideIcon('Home', _Home)
import _Calendar from './calendar-1'
export const Calendar = createLucideIcon('Calendar', _Calendar)
import _CalendarDays from './calendar-days'
export const CalendarDays = createLucideIcon('CalendarDays', _CalendarDays)
import _CalendarPlus from './calendar-add-4'
export const CalendarPlus = createLucideIcon('CalendarPlus', _CalendarPlus)
import _Camera from './camera-1'
export const Camera = createLucideIcon('Camera', _Camera)
import _Play from './play'
export const Play = createLucideIcon('Play', _Play)
import _Pause from './pause'
export const Pause = createLucideIcon('Pause', _Pause)
import _Volume2 from './volume-full'
export const Volume2 = createLucideIcon('Volume2', _Volume2)
import _VolumeX from './volume-off'
export const VolumeX = createLucideIcon('VolumeX', _VolumeX)
import _Image from './images-1'
export const Image = createLucideIcon('Image', _Image)
import _Eye from './eye-open'
export const Eye = createLucideIcon('Eye', _Eye)
import _EyeOff from './eye-slash'
export const EyeOff = createLucideIcon('EyeOff', _EyeOff)
import _AudioLines from './audio-bars'
export const AudioLines = createLucideIcon('AudioLines', _AudioLines)
import _Moon from './moon'
export const Moon = createLucideIcon('Moon', _Moon)
import _Sun from './sun'
export const Sun = createLucideIcon('Sun', _Sun)
import _SunDim from './sun'
export const SunDim = createLucideIcon('SunDim', _SunDim)
import _Heart from './heart'
export const Heart = createLucideIcon('Heart', _Heart)
import _Star from './star'
export const Star = createLucideIcon('Star', _Star)
import _Bookmark from './bookmark'
export const Bookmark = createLucideIcon('Bookmark', _Bookmark)
import _Zap from './zap'
export const Zap = createLucideIcon('Zap', _Zap)
import _Sparkles from './sparkle'
export const Sparkles = createLucideIcon('Sparkles', _Sparkles)
import _File from './file-bend'
export const File = createLucideIcon('File', _File)
import _FileText from './file-text'
export const FileText = createLucideIcon('FileText', _FileText)
import _Folder from './folder-1'
export const Folder = createLucideIcon('Folder', _Folder)
import _FolderOpen from './folder-open'
export const FolderOpen = createLucideIcon('FolderOpen', _FolderOpen)
import _Download from './arrow-inbox'
export const Download = createLucideIcon('Download', _Download)
import _Upload from './arrow-out-of-box'
export const Upload = createLucideIcon('Upload', _Upload)
import _Package2 from './package'
export const Package2 = createLucideIcon('Package2', _Package2)
import _ExternalLink from './square-arrow-top-right'
export const ExternalLink = createLucideIcon('ExternalLink', _ExternalLink)
import _Link from './chain-link-1'
export const Link = createLucideIcon('Link', _Link)
import _Link2 from './chain-link-2'
export const Link2 = createLucideIcon('Link2', _Link2)
import _Lock from './lock'
export const Lock = createLucideIcon('Lock', _Lock)
import _Unlock from './unlocked'
export const Unlock = createLucideIcon('Unlock', _Unlock)
import _Globe from './globus'
export const Globe = createLucideIcon('Globe', _Globe)
import _Phone from './phone'
export const Phone = createLucideIcon('Phone', _Phone)
import _Smartphone from './phone'
export const Smartphone = createLucideIcon('Smartphone', _Smartphone)
import _MapPin from './map-pin'
export const MapPin = createLucideIcon('MapPin', _MapPin)
import _Map from './map'
export const Map = createLucideIcon('Map', _Map)
import _Cloud from './cloud'
export const Cloud = createLucideIcon('Cloud', _Cloud)
import _Code from './code'
export const Code = createLucideIcon('Code', _Code)
import _Code2 from './code-brackets'
export const Code2 = createLucideIcon('Code2', _Code2)
import _Loader from './loader'
export const Loader = createLucideIcon('Loader', _Loader)
import _Loader2 from './loader'
export const Loader2 = createLucideIcon('Loader2', _Loader2)
import _RefreshCw from './arrows-repeat-circle'
export const RefreshCw = createLucideIcon('RefreshCw', _RefreshCw)
import _RefreshCcw from './arrows-repeat-circle'
export const RefreshCcw = createLucideIcon('RefreshCcw', _RefreshCcw)
import _RotateCcw from './arrow-rotate-counter-clockwise'
export const RotateCcw = createLucideIcon('RotateCcw', _RotateCcw)
import _CreditCard from './credit-card-2'
export const CreditCard = createLucideIcon('CreditCard', _CreditCard)
import _ShoppingBag from './shopping-bag-1'
export const ShoppingBag = createLucideIcon('ShoppingBag', _ShoppingBag)
import _Tag from './tag'
export const Tag = createLucideIcon('Tag', _Tag)
import _Tags from './tag'
export const Tags = createLucideIcon('Tags', _Tags)
import _Gift from './gift-1'
export const Gift = createLucideIcon('Gift', _Gift)
import _Ticket from './ticket'
export const Ticket = createLucideIcon('Ticket', _Ticket)
import _LayoutDashboard from './layout-dashboard'
export const LayoutDashboard = createLucideIcon('LayoutDashboard', _LayoutDashboard)
import _LayoutGrid from './layout-grid-1'
export const LayoutGrid = createLucideIcon('LayoutGrid', _LayoutGrid)
import _PanelLeft from './sidebar-simple-left-square'
export const PanelLeft = createLucideIcon('PanelLeft', _PanelLeft)
import _Sidebar from './sidebar'
export const Sidebar = createLucideIcon('Sidebar', _Sidebar)
import _AppWindow from './window-app'
export const AppWindow = createLucideIcon('AppWindow', _AppWindow)
import _Frame from './frame-simple'
export const Frame = createLucideIcon('Frame', _Frame)
import _Square from './square-placeholder'
export const Square = createLucideIcon('Square', _Square)
import _SquareDashed from './square-placeholder-dashed'
export const SquareDashed = createLucideIcon('SquareDashed', _SquareDashed)
import _Quote from './quote'
export const Quote = createLucideIcon('Quote', _Quote)
import _List from './bullet-list'
export const List = createLucideIcon('List', _List)
import _Bold from './bold'
export const Bold = createLucideIcon('Bold', _Bold)
import _Italic from './italic'
export const Italic = createLucideIcon('Italic', _Italic)
import _Underline from './underline'
export const Underline = createLucideIcon('Underline', _Underline)
import _LogOut from './arrow-box-left'
export const LogOut = createLucideIcon('LogOut', _LogOut)
import _LogIn from './login'
export const LogIn = createLucideIcon('LogIn', _LogIn)
import _Laptop from './macbook'
export const Laptop = createLucideIcon('Laptop', _Laptop)
import _Monitor from './imac'
export const Monitor = createLucideIcon('Monitor', _Monitor)
import _Tablet from './phone'
export const Tablet = createLucideIcon('Tablet', _Tablet)
import _Activity from './trending-1'
export const Activity = createLucideIcon('Activity', _Activity)
import _TrendingUp from './trending-4'
export const TrendingUp = createLucideIcon('TrendingUp', _TrendingUp)
import _TrendingDown from './trending-down-simple'
export const TrendingDown = createLucideIcon('TrendingDown', _TrendingDown)
import _PieChart from './pie-chart'
export const PieChart = createLucideIcon('PieChart', _PieChart)
import _LandPlot from './land-plot-simple'
export const LandPlot = createLucideIcon('LandPlot', _LandPlot)
import _Command from './cmd'
export const Command = createLucideIcon('Command', _Command)
import _Terminal from './console'
export const Terminal = createLucideIcon('Terminal', _Terminal)
import _GitCommitVertical from './git-commit-vertical'
export const GitCommitVertical = createLucideIcon('GitCommitVertical', _GitCommitVertical)
import _Slash from './slash-forward'
export const Slash = createLucideIcon('Slash', _Slash)
import _Bed from './bed'
export const Bed = createLucideIcon('Bed', _Bed)
import _Bot from './robot'
export const Bot = createLucideIcon('Bot', _Bot)
import _Clock2 from './clock'
export const Clock2 = createLucideIcon('Clock2', _Clock2)
import _CircleFadingArrowUp from './arrow-up-circle'
export const CircleFadingArrowUp = createLucideIcon('CircleFadingArrowUp', _CircleFadingArrowUp)
import _Dot from './dot-small'
export const Dot = createLucideIcon('Dot', _Dot)
import _Footprints from './footsteps'
export const Footprints = createLucideIcon('Footprints', _Footprints)
import _GalleryHorizontalEnd from './albums'
export const GalleryHorizontalEnd = createLucideIcon('GalleryHorizontalEnd', _GalleryHorizontalEnd)
import _GalleryVerticalEnd from './albums'
export const GalleryVerticalEnd = createLucideIcon('GalleryVerticalEnd', _GalleryVerticalEnd)
import _HelpCircle from './circle-questionmark'
export const HelpCircle = createLucideIcon('HelpCircle', _HelpCircle)
import _LifeBuoy from './rescue-ring'
export const LifeBuoy = createLucideIcon('LifeBuoy', _LifeBuoy)
import _Popcorn from './popcorn'
export const Popcorn = createLucideIcon('Popcorn', _Popcorn)
import _Waves from './waves-simple'
export const Waves = createLucideIcon('Waves', _Waves)
